#ifndef CONFIG_H
#define CONFIG_H

#define TOTAL_INTERRUPTS 256

#define KERNEL_HEAP_FREE_BIN_HEAD 0x00007E00

#define KERNEL_STACK_BASE 0x600000

#define SECTOR_SZ 512

#define MEMORY_BASE 0
#define MEMORY_LIMIT 0xffffffff

#endif